### ISSUE TITLE
How get the value in x-wp-totalpages header

### ISSUE THREAD

**Issue by jairgarcia** [woothemes/wc-api-node#23]
I need to know, how i get the header value of x-wp-totalpages, this is my code:

WooCommerce.get( 'products', function( err, data, res ) {
              console.log('data: ' , data);
              console.log('header:  ' , res.getReponseHeader('x-wp-totalpages'));
});

Thanks.

**Comment by claudiosmweb** [comment]
It's only on array:

```js
console.log('header: ' , data.headers['x-wp-totalpages']);
```

**Comment by josh-** [comment]
@claudiosmweb thanks – this helped me out 👍 

Just quickly thought I'd mention that I think there's a typo in your response, it should be `headers['x-wc-totalpages']` instead of `data.headers['x-wp-totalpages']` according to the [documentation](https://github.com/woothemes/woocommerce-rest-api-docs/blob/master/source/includes/v2/_introduction.md#pagination)?

**Comment by claudiosmweb** [comment]
@josh- nop, if you are using this with the WP REST API integration, will use `x-wp` and not `x-wc`.
