### ISSUE TITLE
What's the best way to detect the Woocommerce version.

### ISSUE THREAD

**Issue by paulogr** [woothemes/wc-api-node#31]
This is just a question, not an issue, but I appreciate If someone can help me.

How could I know before hand the Woocommerce and WP version to determine the API version and prefix to be used ?

Based on Woocommerce and WP version I have to know if I need to use **wp-json** or **wc-api** and which version, right?

Any ideas? Thank you!

**Comment by luciancapdefier** [comment]
`
var WooCommerceAPI = require('woocommerce-api');

var WooCommerce = new WooCommerceAPI({
  url: '...',
  consumerKey: '...',
  consumerSecret: '...',
});

console.log(WooCommerce);

console.log('+++');
`




-sh-4.1$ node wc-test.js 
WooCommerceAPI {
  classVersion: '1.4.0',
  url: 'http://dev.woo.report',
  wpAPI: false,
  wpAPIPrefix: 'wp-json',
  version: 'v3',
  isSsl: false,
  consumerKey: 'ck_62fe40b969eff65976a9e49d4ac00d19e3d76d7e',
  consumerSecret: 'cs_65493da5f6649235b52007433544712768d1bc0d',
  verifySsl: true,
  encoding: 'utf8',
  queryStringAuth: false,
  port: '',
  timeout: undefined }
+++


wpAPI will tell you if the wc and wp apis are integrated; is false, then it's wc-api/vX/route, otherwise, it's wp-json/wc/v1/route

**Comment by luciancapdefier** [comment]
version tells you latest version of wc api

**Comment by claudiosmweb** [comment]
Not a question related to this wrapper, you should ask it in https://wordpress.org/support/plugin/woocommerce
