### ISSUE TITLE
Issues with the wpAPI: false option

### ISSUE THREAD

**Issue by theshaune** [woothemes/wc-api-node#33]
If I read the [Woo Docs](https://woothemes.github.io/woocommerce-rest-api-docs/?shell#requirements), it says The WP rest API doesn't need to be installed...

When I run the following code **without the wpAPI set to true**, the response is '-1', however, when i add the wpAPI: true, the API works as intended.

I don't have the WP Rest Plugin installed, I'm not sure if this issue is jut a misunderstanding on my part? Any further explanation to help me understand what is going on would be fantastic, thanks

```
var WooCommerce = new WooCommerceAPI({
  url: 'https://example.com',
  wpAPI: true, // <-- this
  version: 'wc/v1',
  consumerKey: 'ck_xxx',
  consumerSecret: 'cs_xxx',
  queryStringAuth: true 
});

WooCommerce.get('products').then(function(result) {
   console.log(JSON.parse(result.toJSON().body));
});
```

**Comment by theshaune** [comment]
If it is any help, the basic auth works fine in postman, eg. https://example.com/wp-json/wc/v1/products/

**Comment by claudiosmweb** [comment]
`wpAPI: true` means to use our new integration with the WordPress REST API... And in the docs we said that you don't need to install the WP-API plugin... Two different this...

This is a patch for the WordPress REST API that is on core since WordPress 4.4: `https://example.com/wp-json`.
But you don't need the WP-API plugin that includes endpoints for posts, pages and etc.

**Comment by claudiosmweb** [comment]
In other words, `wpAPI: true` define if should use the `/wp-json` path or the legacy `/wc-api`.
